#!/bin/sh

case $1 in
    start)
        /usr/sbin/module_load hello
        /usr/sbin/module_load faulty
        /usr/sbin/scull_load
        ;;
    stop)
        /usr/sbin/module_unload hello
        /usr/sbin/module_unload faulty
        /usr/sbin/scull_unload
        ;;
    *)
        echo "Usage: $0 {start|stop}"
    exit 1
esac

exit 0